Repository googleapis/python-grpc-google-iam-v1, pull requests merged in 2023-11, with the labels that each got.

#31 fix: add classifier for python 3.11
  setup.py
Labels: automerge, api: iam, size: xs

#58 build: add docs configuration
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  owlbot.py
Labels: api: iam, size: m

#60 build: add docs
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  README.rst
  docs/CHANGELOG.md
  docs/README.rst
  docs/_static/custom.css
  docs/_templates/layout.html
  docs/conf.py
  docs/iam_v1/services_.rst
  docs/iam_v1/types_.rst
  docs/index.rst
  noxfile.py
  owlbot.py
Labels: api: iam, size: l

#62 build: add .trampolinerc
  .trampolinerc
  owlbot.py
Labels: api: iam, size: m

#63 chore: update template to enable docs generation
  .kokoro/docs/common.cfg
  owlbot.py
Labels: api: iam, size: s

#59 feat: Introduce compatibility with native namespace packages
  .github/sync-repo-settings.yaml
  .github/workflows/unittest.yml
  google/iam/__init__.py
  noxfile.py
  owlbot.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.12.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
  tests/unit/test_google_iam.py
  tests/unit/test_packaging.py
Labels: api: iam, size: m

#68 chore: remove custom sync-repo-settings
  .github/sync-repo-settings.yaml
Labels: api: iam, size: s

#69 build: treat warnings as errors
  pytest.ini
Labels: api: iam, size: xs
